import "./globals.css";
import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "@/component/Home/Footer/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
